score = Score()
melody = Staff()
score.add_staff(melody)
melody.add_signature("3/4")
melody.add_key("Eb major")
melody.add_clef("treble")
melody.add_notes(["Eb 4 2 4 upbow ff staccato", ["G 4", "a 1", "4 fermata downbow"], "E 4 8", "C# 4 8", "R 4", "d 7 4", ["f -1", "a 2", "2"], "R 4"])
melody.add_signature("4/8")
melody.add_key("c minor")
melody.add_clef("alto")
melody.add_notes(["Eb 4 2", "G 4 4", "E 4 8", "C# 4 8", "R 2", "d 7 4", "f# 5 4"])
score.add_lyrics("This is a test song")
score.generate_lilypond("ltest.ly")
