from MusicGuide.src.main import *

score = Score()
melody = Staff()
score.add_staff(melody)
melody.add_signature("3/4")
melody.add_key("Eb major")
melody.add_clef("treble")
melody.add_notes(["Eb 4 2 4 upbow ff staccato", ["G 4", "a 1", "4 downbow accent"], "E 4 8 tenuto", "C# 4 8 coda", "R 4", "d 7 4 turn", ["f -1", "a 2", "2"], "R 4"])
melody.add_signature("4/8")
melody.add_key("c minor")
melody.add_clef("alto")
melody.add_notes(["Eb 4 2 mordent", "G 4 4 <", "E 4 8 !", "C# 4 8 >", "R 2", "d 7 4 ppp", "f# 5 4 verylongfermata"])
score.add_lyrics("Quest-ions?")
score.add_header("Thank You!", "Kavya & Sophia")
score.generate_lilypond("example.ly")
